[env:esp32s3]
; 1. PlatformIO hybrid framework
platform = espressif32
framework = espidf, arduino
board = esp32-s3-devkitc-1
monitor_speed = 115200


; 2. Match the exact 16MB Flash and Min SPIFFS allocation scheme 
board_build.arduino.upstream_packages = yes
board_build.flash_mode = dio          
board_build.f_flash = 80000000L
board_upload.flash_size = 16MB
board_build.filesystem = littlefs
board_build.partitions = partitions.csv ;partitions_default.csv

; 3. Clean routing definitions for Host-Only Mode
build_unflags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

build_flags = 
    -DARDUINO_USB_MODE=0
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DCONFIG_ASYNC_TCP_RUNNING_CORE=1


board_build.esp-idf.sdkconfig =
    CONFIG_FREERTOS_HZ=1000

lib_deps = 
    adafruit/Adafruit SSD1306@^2.5.7
    adafruit/Adafruit GFX Library@^1.11.5
    ;h2zero/NimBLE-Arduino@ ^2.1.0
    bblanchon/ArduinoJson@^7.0.4
    igorantolic/Ai Esp32 Rotary Encoder@^1.7
    ;lathoub/BLE-MIDI
	;sauloverissimo/ESP32_Host_MIDI@^7.0.0
    tttapa/Control Surface@^2.1.0

platform_packages =
    tool-mklittlefs
         
; Build configuration
build_type = release ;debug
upload_speed = 921600
; --- Target upload port configuration ---
;upload_port = COM8

; --- OTA Upload Options ---
; The mDNS name of the device (e.g., rockibot.local).
; Or, you can use the device's IP address if mDNS discovery fails.
upload_protocol = espota
upload_port = 192.168.1.36